apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-config
  namespace: hackathon
data:
  DB_HOST: hackathon-postgres.cnikyioceitn.ap-south-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: hackathonadmin
  DB_SSLMODE: require
  AWS_REGION: ap-south-1
  COGNITO_REGION: ap-south-1
  COGNITO_USER_POOL_ID: ap-south-1_sfpWo53YF
  COGNITO_APP_CLIENT_ID: b56eo5k1q1ffcpsto6jrkj7ov
  S3_BUCKET: hackathon-588199412082
  TEAM_SERVICE_URL: http://team-service.hackathon.svc.cluster.local
  SUBMISSION_SERVICE_URL: http://submission-service.hackathon.svc.cluster.local
